version: '3'
services:
  blockchain:
    container_name: blockchain
    image: blockchain:latest
    entrypoint: python3 /main.py
    environment:
      - BLOCKCHAIN_HOST=0.0.0.0
      - BLOCKCHAIN_PORT=12345
      - BLOCKCHAIN_LISTENERS=5
      - QUERY_HOST=0.0.0.0
      - QUERY_PORT=12344
      - QUERY_LISTENERS=1
      - N_READERS=5
    networks:
      - blockchain_network

  mining:
    container_name: mining
    image: mining:latest
    entrypoint: python3 /main.py
    environment:
      - N_MINERS=5
      - BLOCKCHAIN_HOST=blockchain
      - BLOCKCHAIN_PORT=12345
      - API_PORT=8080
      - API_LISTENERS=5
      - QUERY_HOST=blockchain
      - QUERY_PORT=12344
      - TIMEOUT_CHUNK=5
      - LIMIT_CHUNK=200
      - N_CLIENTS=1
    networks:
      - blockchain_network
    ports:
      - "8080:8080"
    depends_on: 
      - blockchain

networks:
  blockchain_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
